### ISSUE TITLE
@lru_cache causes Error with Python3.7

### ISSUE THREAD

**Issue by jeromemassot** [VoIlAlex/appdata#2]
Hi Alex,

I have found this little problem with your module when using Python 3.7.

You have used the decorator lru_cache for the get_home_folder method but apparently, if I have understood correctly the error returned by python and the StackOverflow posts, the rlu_cache method cannot be called without argument in Python versions before 3.8.

 @lru_cache
 def get_home_folder():

So, two possible fixes:
1- Need Python 3.8+
2- Add  ( ) to the decorator (Not sure about this one)

What do you think?

Best regards

Jerome

**Comment by VoIlAlex** [comment]
Excuse me for the late notice. 

PR fixing the issue - https://github.com/VoIlAlex/appdata/pull/5.
It will be available in `appdata` version 2.2.0.
